apiVersion: v1
kind: Secret
metadata:
    name: lp-generator-secret
    namespace: {{ .Values.namespace }}
type: Opaque
stringData:
    config.yaml: |
      S3MetadataBucket:
        url: {{ .Values.s3MetadataBucket.url }}
        accesskey: {{ .Values.s3MetadataBucket.accesskey }}
        secretkey: {{ .Values.s3MetadataBucket.secretkey }}
        bucket: {{ .Values.s3MetadataBucket.bucket }}
        region: {{ .Values.s3MetadataBucket.region }}
      S3DeploymentBucket:
        url: {{ .Values.s3DeploymentBucket.url }}
        accesskey: {{ .Values.s3DeploymentBucket.accesskey }}
        secretkey: {{ .Values.s3DeploymentBucket.secretkey }}
        bucket: {{ .Values.s3DeploymentBucket.bucket }}
        region: {{ .Values.s3DeploymentBucket.region }}