apiVersion: v1
kind: Service
metadata:
  name: landing-pages-service
  namespace: {{ .Values.namespace }}
spec:
  externalName: {{ .Values.s3Host }}
  sessionAffinity: None
  type: ExternalName
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443