version: "3.7"
services:
  minio:
    command: server /data
    container_name: s3
    environment:
      - MINIO_ACCESS_KEY=myaccesskey
      - MINIO_SECRET_KEY=mysecretkey
    healthcheck:
      test: ["CMD", "curl", "-fkq", "https://127.0.0.1:9000/minio/health/live"]
      interval: 5s
      timeout: 20s
      retries: 3
    image: minio/minio:RELEASE.2020-10-28T08-16-50Z
    ports:
      - "9000:9000"