---
name: Lint

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Super-linter
        uses: super-linter/super-linter@4ce20838b8ab83717e78138c5b3a1407148e0918
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: (index\.md|charts/.*)
          VALIDATE_MARKDOWN: true
          MARKDOWN_CONFIG_FILE: .markdownlint.json
          VALIDATE_TRIVY: true
          VALIDATE_GO: true
          VALIDATE_CSS: true
          VALIDATE_CSS_PRETTIER: true
          VALIDATE_GO_MODULES: true
          TRIVY_CONFIG_FILE: trivy.yaml
