baseurl = "https://datasets.bp.nbis.se"
title = "Bigpicture datasets"
languageCode = "en-us"

uglyURLs = true
[params]
  header_image = "img/bigpicture-banner.jpg"
  SEOTitle = "Bigpicture datasets"
  slogan = "Production site for Bigpicture landing pages"

  image_404 = "img/404-bg.jpg"

  # Sidebar settings
  sidebar_about_description = "Bigpicture dataset description pages"
  sidebar_avatar = "img/bigpicture_logo.svg"      # use absolute URL, seeing it's used in both `/` and `/about/`
